### PR TITLE
Phoenixd Server Wallet

### PR DESCRIPTION
**Pull request by hkarani**
@john-zaprite 

Here is the PR of the wallet alongside installation instructions for both Start9Os and Umbrel

### CODE REVIEW

**Comment by john-zaprite** [comment]
Nice work @hkarani

I haven't been able to sideload the pkg due to an upload error I'm getting on my StartOS:
```
phoenixd-lightning-wallet-ui - Install Failed
Install of phoenixd-lightning-wallet-ui@0.1.0 Failed: Filesystem I/O 
Error: error reading a body from connection: end of file before message length reached
```

However, here are our initial thoughts/recommendations…

1. Use the same name and match the case for the API calls. For example: 
- Rename `api/create-invoice` to `api/createinvoice` and same for the other calls.
2. If Start9 releases the `phoenixd` app (I think it's still in the Alpha registry?) then use that as a dependency for the GUI instead of embedding it. This does not apply to Umbrel since I don't think anyone created a standalone app for `phoenixd` yet.

**Comment by hkarani** [comment]
Thank you for reviewing this, @john-zaprite. I'll make the changes right away.

The installation error on Start9OS is likely due to an existing phoenixd instance already running. This prevents the app from running with its own embedded phoenixd instance, as they both require the same location on the Start9 filesystem to store wallet data.

Configuring the app to use the existing phoenixd instance as recommended in option 2 can resolve this. This way, only one phoenixd instance will be active, which should eliminate the conflict.

**Comment by john-zaprite** [comment]
Ah ok great, thanks for the clarification. I do have the Start 9's instance of `phoenixd` installed—so that's likely it. I'll remove it and test again and report back.

**Comment by hkarani** [comment]
@john-zaprite  Did some tests running the wallet UI alongside the phoenixd service from the registry, seems to work fine and install even with phoenixd already installed.

Installing the wallet UI picks up the wallet config of the already installed phoenixd service.

The start9 server I'm testing on is running on a VM, could that be the difference causing the issue?

**Comment by hkarani** [comment]
Thanks for letting me know. I'll still try to see if I can resolve this.

**Comment by hkarani** [comment]
Updated changes standardize the api route names and sets the GUI to use to configuration of phoenixd if it already already installed.

**Pull request merged**
